apiVersion: v1
kind: ReplicationController
metadata:
  name: reactive-app-rc
  labels:
    tier: backend
    app: reactive-app-demok8s
spec:
  replicas: 3
  template:
    metadata:
      name: reactive-app-pod
      labels:
        tier: backend
        app: reactive-app-demok8s
    spec:
      containers:
        - name: reactive-app
          image: catallicpankaj/reactiveapp1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080